### ISSUE TITLE
Implement Insight API

### ISSUE THREAD

**Issue by BoBeR182** [gdassori/gangsta#7]
I don't understand a lot of JavaScript yet, but it seems that we could incorporate https://github.com/bitpay/insight-api as a back end for rebroadcasting transactions, as well as unconfirmed spends.

Anyone want to help me make the code base less dependent on gangsta.strangled.net

**Comment by gdassori** [comment]
gangsta js is already insight-api compliant for transactions pushing.
If you manage an insight-api installation on an rbf patched bitcoincore, it should works.
I haven't used insight, but my own backend, on where I've replicated the insight-api pushtx feature, so I say "it should". If it wouldn't, anyway, a fix should be easy.
However, gangsta.strangled.net servers just handle the signed tx, so you shouldn't care about private keys exposure, if you run it locally, in a safe environment. (I saw your bitcointalk thread).

About the unconfirmed spends, instead, is different. 
The way insight-api handle transactions is a little more "low level" than the blockr api, so is not a "one minute job", to make gangsta third-party independant.
