### ISSUE TITLE
Cannot push transaction

### ISSUE THREAD

**Issue by BoBeR182** [gdassori/gangsta#8]
![screenshot from 2015-03-23 11 48 28](https://cloud.githubusercontent.com/assets/525433/6785048/aed65f0a-d159-11e4-9ef9-6b4b3fd9ef95.png)

Any ideas? This is on the http://gangsta.strangled.net/ and I had the same issue running it locally.

**Comment by gdassori** [comment]
Introduced (and fixed) a bug in the latest backend rel.
Thanks for feedback.

**Comment by BoBeR182** [comment]
Care to open source your backend code? Will test and post back results.

**Comment by BoBeR182** [comment]
Transaction broadcasting

Transaction has been rejected by gangsta node. Check the FAQ for possible reasons

**Comment by gdassori** [comment]
Retry now. 
I am sorry but I'm not thinking about publishing the backend, and this is why I have choosen to do gangsta "insight api compliant" on the push part.
